# Generated by Django 3.1.7 on 2021-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0003_auto_20210915_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='Ref_code',
            field=models.CharField(default='af1212', max_length=10000),
            preserve_default=False,
        ),
    ]
