# Generated by Django 3.1.7 on 2021-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0005_auto_20210916_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='Ref_code',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
