# Generated by Django 3.1.7 on 2021-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0006_auto_20210916_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='first_or_second',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], max_length=20, null=True),
        ),
    ]
