# Generated by Django 3.1.7 on 2021-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0009_auto_20210923_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='date_taken',
            field=models.DateField(auto_now_add=True),
        ),
    ]
