# Generated by Django 3.1.7 on 2022-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0010_auto_20210923_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationKitSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_sn_no', models.CharField(max_length=1000)),
                ('number_of_kits', models.IntegerField(default=0)),
                ('date_of_delivery', models.DateField()),
            ],
            options={
                'verbose_name': 'VaccinationKit',
                'verbose_name_plural': 'VaccinationKits',
            },
        ),
        migrations.AddField(
            model_name='labcenter',
            name='remaining_testing_kits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labcenter',
            name='remaining_vaccines',
            field=models.IntegerField(default=0),
        ),
    ]
